# Generated by Django 4.0.3 on 2022-04-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiFunctions', '0006_category_rename_categoryname_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='', max_length=500),
        ),
    ]
