# Generated by Django 4.0.3 on 2022-04-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiFunctions', '0007_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.IntegerField(),
        ),
    ]
