# Generated by Django 4.0.3 on 2022-04-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiFunctions', '0008_alter_product_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
