# Generated by Django 4.0.3 on 2022-04-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiFunctions', '0010_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
